<!---table class="table">
        <tr><td>
            <div class="btn-box-row row-fluid">
                <a href="<?php //echo site_url('Test/Edt_controller');?>" >
                   <button type="button" class="btn-box big span12" data-toggle="modal" data-target="#myModal">
                        <i class="icon-gift" id="btnaddclass"name="btnaddclass"></i>
                      <b>INTERNAL-EXAM-1</b>
                    </button>
                  </a>
              </div>
                </td>
    
                <td>
                   <div class="btn-box-row row-fluid "">
                <a href="<?php echo site_url('Test/Edt_controller');?>" >
                   <button type="button" class="btn-box big span12" data-toggle="modal" data-target="#myModal">
                        <i class="icon-gift" id="btnaddclass"name="btnaddclass"></i>
                      <b>INTERNAL-EXAM-2</b>
                    </button>
                  </a>
              </div>

                </td>

                </tr>
                <tr>
                  <td>
                <div class="btn-box-row row-fluid  ">
                      <a href="<?php echo site_url('Test/Edt_controller');?>" >
                         <button type="button" class="btn-box big span12" data-toggle="modal" data-target="#myModal">
                              <i class="icon-gift" id="btnaddclass"name="btnaddclass"></i>
                            <b>CLASS-TEST</b>
                          </button>
                        </a>
                    </div>
                

                </td>
              
                <td>
                  

                  <div class="btn-box-row row-fluid "style=" float: right;">
                      <a href="<?php echo site_url('Test/Edt_controller');?>" >
                         <button type="button" class="btn-box big span12" data-toggle="modal" data-target="#myModal">
                              <i class="icon-gift" id="btnaddclass"name="btnaddclass"></i>
                            <b>ASSIGNMENT-MARKS</b>
                          </button>
                        </a>
                    </div>

                </td>

              </tr>             
              
              <tr>
                <td  colspan="2">
                    <div class="btn-box-row row-fluid ">
                      <a href="<?php echo site_url('Test/Edt_controller');?>" >
                         <button type="button" class="btn-box big span12" data-toggle="modal" data-target="#myModal">
                              <i class="icon-adjust" id="btnaddclass"name="btnaddclass"></i>
                            <b>LAB-MARKS</b>
                          </button>
                        </a>
                    </div>
                    <td>
              </tr>
              </table----><div class="span9">
	<div class="content">
		<div class="module">
			<div class="module-head">
					<h1>EDIT -MARKS</h1>
			</div>
		<div class="module-body">
			<div class="control-group ">
				<div class="module">
                         <div class="module-head">
                                <h3>
                                  SELECT YOUR CHOICE
                              </h3>
                            </div>
                            <div class="module-body">
                             <div id="hover">
                             	<div class="btn-box-row row-fluid" >
      
                             	<div class="btn-box-row row-fluid  btn-box big span4"style=" float: left; color: #000090;">
        					<div class="class"> 
           								<a href="<?php echo site_url('main/takeattendance_controller');?>">
           								<div class="btn-box-row row-fluid span2" style="font-size: 11px !important; text-align: left">
         						 <td class="myclassblock">
                              			 INTERNAL MARKS

           							 </td>
      						</div>
      						<div class="btn-box-row row-fluid  btn-box big span4"style=" float: left; color: #000090;">
        					<div class="class"> 
           								<a href="<?php echo site_url('main/takeattendance_controller');?>">
           								<div class="btn-box-row row-fluid span2" style="font-size: 11px !important; text-align: left">
         						 <td class="myclassblock">
                              			 INTERNAL MARKS

           							 </td>
      						</div>
      						<div class="btn-box-row row-fluid  btn-box big span4"style=" float: left; color: #000090;">
        					<div class="class"> 
           								<a href="<?php echo site_url('main/takeattendance_controller');?>">
           								<div class="btn-box-row row-fluid span2" style="font-size: 11px !important; text-align: left">
         						 <td class="myclassblock">
                              			 INTERNAL MARKS

           							 </td>
      						</div>
         
      					</div>

      </a>
    </div>
      
</div>
 </div>
  

									<div class="control-group ">
											<label class="control-label " for="basicinput">Dropdown Button</label>
											<div class="controls">
												<div class="dropdown">
													<a class="dropdown-toggle btn" data-toggle="dropdown" href="#">Dropdown Button <i class="icon-caret-down"></i></a>
													<ul class="dropdown-menu"  role="menu" aria-labelledby="dLabel">
														<li><a href="#">First Row</a></li>
														<li><a href="#">Second Row</a></li>
														<li><a href="#">Third Row</a></li>
														<li><a href="#">Fourthli</a></li>
													</ul>
												</div>
											</div>
									</div>

                              </div>
                           </div>
                 </div>

			</div>
		</div>
									
	</div>
</div>
</div>
